import React, { useState, useEffect } from 'react';
import { Translation, Post, Comment, LanguageCode } from '../types';
import { getPosts, savePost, saveComment, likePost } from '../services/boardService';
import { IDEOLOGIES } from '../constants';

interface BoardProps {
  translations: Translation;
  language: LanguageCode;
  onBack: () => void;
}

const Board: React.FC<BoardProps> = ({ translations, language, onBack }) => {
  const [activeTab, setActiveTab] = useState<'community' | 'guide'>('community');
  const [posts, setPosts] = useState<Post[]>([]);
  const [view, setView] = useState<'list' | 'create' | 'detail'>('list');
  const [selectedPost, setSelectedPost] = useState<Post | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // Form State
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [author, setAuthor] = useState('');

  // Comment Form State
  const [commentContent, setCommentContent] = useState('');
  const [commentAuthor, setCommentAuthor] = useState('');

  useEffect(() => {
    refreshPosts();
  }, []);

  const refreshPosts = async () => {
    setIsLoading(true);
    const fetchedPosts = await getPosts();
    // Convert Firestore ISO dates to readable local dates if needed, or keep as string
    // For simplicity, we assume they are strings that can be displayed or formatted.
    const formattedPosts = fetchedPosts.map(p => ({
        ...p,
        date: p.date.includes('T') ? new Date(p.date).toLocaleDateString() : p.date
    }));
    setPosts(formattedPosts);
    setIsLoading(false);
  };

  const handleCreatePost = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !content.trim()) return;

    const newPost: Post = {
      id: '', // ID will be generated by Firestore
      title,
      content,
      author: author || 'Anonymous',
      date: new Date().toISOString(),
      comments: [],
      likes: 0
    };

    setIsLoading(true);
    await savePost(newPost);
    await refreshPosts();
    setIsLoading(false);
    
    setView('list');
    setTitle('');
    setContent('');
    setAuthor('');
  };

  const handleCreateComment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!commentContent.trim() || !selectedPost) return;

    const newComment: Comment = {
      id: Date.now().toString(),
      content: commentContent,
      author: commentAuthor || 'Anonymous',
      date: new Date().toLocaleDateString(),
    };

    // If it's a real post (from Firebase), save the comment
    // If it's a guide post (ID starts with 'guide-'), we don't save comments in this demo
    if (!selectedPost.id.startsWith('guide-')) {
        await saveComment(selectedPost.id, newComment);
        
        // Optimistic update for UI
        const updatedPost = { ...selectedPost, comments: [...selectedPost.comments, newComment] };
        setSelectedPost(updatedPost);
        
        // Refresh background data
        refreshPosts(); 
    } else {
        alert("Comments are disabled for guide posts in this demo.");
    }
    
    setCommentContent('');
    setCommentAuthor('');
  };

  const handleLike = async (e: React.MouseEvent, postId: string) => {
      e.stopPropagation();
      if (!postId.startsWith('guide-')) {
          await likePost(postId);
          // Optimistic update
          if(selectedPost && selectedPost.id === postId) {
              setSelectedPost({ ...selectedPost, likes: (selectedPost.likes || 0) + 1});
          }
          // Refresh actual data
          refreshPosts();
      }
  }

  // --- Render Functions ---

  const renderCreateView = () => (
    <div className="w-full max-w-2xl mx-auto animate-fade-in-up">
      <h2 className="text-3xl font-bold text-gray-900 mb-6">{translations.createPost}</h2>
      <form onSubmit={handleCreatePost} className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100">
        <div className="mb-4">
          <input
            type="text"
            placeholder={translations.postTitlePlaceholder}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full text-xl font-bold border-b border-gray-200 py-2 focus:outline-none focus:border-blue-500 placeholder-gray-300"
            required
          />
        </div>
        <div className="mb-4">
          <input
            type="text"
            placeholder={translations.authorPlaceholder}
            value={author}
            onChange={(e) => setAuthor(e.target.value)}
            className="w-full text-sm text-gray-600 border-b border-gray-200 py-2 focus:outline-none focus:border-blue-500 placeholder-gray-300"
          />
        </div>
        <div className="mb-6">
          <textarea
            placeholder={translations.postContentPlaceholder}
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full h-40 text-gray-700 resize-none focus:outline-none placeholder-gray-300"
            required
          />
        </div>
        <div className="flex justify-end space-x-3">
          <button
            type="button"
            onClick={() => setView('list')}
            className="px-6 py-2.5 rounded-full text-gray-500 font-medium hover:bg-gray-100 transition-colors"
          >
            {translations.cancel}
          </button>
          <button
            type="submit"
            disabled={isLoading}
            className="px-6 py-2.5 bg-blue-600 text-white rounded-full font-medium hover:bg-blue-700 shadow-md transition-all disabled:opacity-50"
          >
            {isLoading ? '...' : translations.submit}
          </button>
        </div>
      </form>
    </div>
  );

  const renderDetailView = () => {
    if (!selectedPost) return null;
    const isGuide = selectedPost.id.startsWith('guide-');

    return (
      <div className="w-full max-w-3xl mx-auto animate-fade-in">
        <button 
          onClick={() => setView('list')} 
          className="mb-4 text-gray-500 hover:text-gray-900 flex items-center transition-colors"
        >
          <svg className="w-5 h-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7"/></svg>
          {translations.back}
        </button>

        <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-gray-100 mb-8">
          <div className="p-8 md:p-10">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">{selectedPost.title}</h1>
            <div className="flex items-center text-sm text-gray-500 mb-8 space-x-4">
              <span className={`font-medium px-2 py-1 rounded-md ${isGuide ? 'bg-purple-50 text-purple-600' : 'bg-blue-50 text-blue-600'}`}>
                  {selectedPost.author}
              </span>
              <span>{selectedPost.date}</span>
              {!isGuide && (
                  <button onClick={(e) => handleLike(e, selectedPost.id)} className="flex items-center space-x-1 hover:text-red-500 transition-colors">
                      <svg className="w-4 h-4" fill={selectedPost.likes > 0 ? "currentColor" : "none"} stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/></svg>
                      <span>{selectedPost.likes || 0}</span>
                  </button>
              )}
            </div>
            <div className="prose max-w-none text-gray-700 text-lg leading-relaxed whitespace-pre-wrap">
              {selectedPost.content}
            </div>
          </div>
        </div>

        {!isGuide && (
            <div className="bg-white/60 backdrop-blur-md rounded-3xl p-6 md:p-8 shadow-sm">
            <h3 className="text-xl font-bold text-gray-900 mb-6">{translations.comments} ({selectedPost.comments.length})</h3>
            
            <form onSubmit={handleCreateComment} className="mb-8">
                <div className="flex flex-col space-y-3">
                <input
                    type="text"
                    placeholder={translations.authorPlaceholder}
                    value={commentAuthor}
                    onChange={(e) => setCommentAuthor(e.target.value)}
                    className="w-full md:w-1/2 px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                />
                <div className="relative">
                    <textarea
                    placeholder={translations.addComment}
                    value={commentContent}
                    onChange={(e) => setCommentContent(e.target.value)}
                    className="w-full px-4 py-3 pr-12 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white resize-none h-24"
                    required
                    />
                    <button 
                    type="submit"
                    className="absolute bottom-3 right-3 p-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                    >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/></svg>
                    </button>
                </div>
                </div>
            </form>

            <div className="space-y-4">
                {selectedPost.comments.length === 0 ? (
                    <p className="text-gray-400 text-center py-4 italic">No comments yet.</p>
                ) : (
                    selectedPost.comments.slice().reverse().map((comment) => (
                    <div key={comment.id} className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm animate-fade-in">
                        <div className="flex justify-between items-start mb-2">
                        <span className="font-bold text-gray-800 text-sm">{comment.author}</span>
                        <span className="text-xs text-gray-400">{comment.date}</span>
                        </div>
                        <p className="text-gray-600">{comment.content}</p>
                    </div>
                    ))
                )}
            </div>
            </div>
        )}
      </div>
    );
  };

  const renderListView = () => {
    // Determine which posts to show based on tab
    let displayPosts: Post[] = [];

    if (activeTab === 'community') {
        displayPosts = posts;
    } else {
        // Generate Guide posts dynamically from IDEOLOGIES constant
        displayPosts = IDEOLOGIES[language].map((quadrant, index) => {
            // Construct content
            let content = `${quadrant.description}\n\n`;
            content += quadrant.items.map(item => `### ${item.name}\n${item.definition}\n${item.explanation}`).join('\n\n');

            return {
                id: `guide-${index}`,
                title: quadrant.name,
                content: content,
                author: 'PolitiCompass Guide',
                date: '-',
                comments: [],
                likes: 0
            }
        });
    }

    return (
        <div className="w-full max-w-5xl mx-auto">
        <div className="flex flex-col md:flex-row justify-between items-center mb-8">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 tracking-tight mb-4 md:mb-0">{translations.boardTitle}</h2>
            {activeTab === 'community' && (
                <button
                onClick={() => setView('create')}
                className="px-6 py-3 bg-gray-900 text-white rounded-full font-medium shadow-lg hover:bg-black hover:scale-105 transition-all duration-300 flex items-center space-x-2"
                >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4"/></svg>
                <span>{translations.newPost}</span>
                </button>
            )}
        </div>

        {/* Tab Switcher */}
        <div className="flex space-x-1 mb-8 bg-gray-200/50 p-1 rounded-xl w-fit mx-auto md:mx-0">
            <button
                onClick={() => setActiveTab('community')}
                className={`px-6 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                    activeTab === 'community' 
                    ? 'bg-white text-gray-900 shadow-sm' 
                    : 'text-gray-500 hover:text-gray-900'
                }`}
            >
                {translations.communityTab}
            </button>
            <button
                onClick={() => setActiveTab('guide')}
                className={`px-6 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                    activeTab === 'guide' 
                    ? 'bg-white text-gray-900 shadow-sm' 
                    : 'text-gray-500 hover:text-gray-900'
                }`}
            >
                {translations.guideTab}
            </button>
        </div>

        {isLoading && activeTab === 'community' ? (
             <div className="flex justify-center py-20">
                <div className="w-10 h-10 border-4 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
             </div>
        ) : displayPosts.length === 0 ? (
            <div className="text-center py-20 bg-white/50 backdrop-blur rounded-3xl border border-dashed border-gray-300">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-400">
                <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg>
            </div>
            <p className="text-gray-500 text-lg">{translations.noPosts}</p>
            </div>
        ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {displayPosts.map((post) => (
                <div 
                key={post.id} 
                onClick={() => { setSelectedPost(post); setView('detail'); }}
                className="bg-white rounded-3xl p-6 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 border border-gray-100 cursor-pointer group flex flex-col h-64"
                >
                <div className="flex-1">
                    <div className="flex justify-between items-start mb-3">
                        <span className={`text-xs font-bold px-2 py-1 rounded-md uppercase tracking-wide ${activeTab === 'guide' ? 'bg-purple-50 text-purple-600' : 'bg-blue-50 text-blue-600'}`}>
                            {post.author}
                        </span>
                        <span className="text-xs text-gray-400">{post.date}</span>
                    </div>
                    <h3 className="text-xl font-bold text-gray-900 mb-3 group-hover:text-blue-600 transition-colors line-clamp-2">{post.title}</h3>
                    <p className="text-gray-500 line-clamp-3 leading-relaxed whitespace-pre-wrap">{post.content}</p>
                </div>
                
                <div className="mt-4 pt-4 border-t border-gray-50 flex justify-between items-center text-sm text-gray-400">
                    <div className="flex items-center space-x-4">
                        <span className="flex items-center space-x-1">
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg>
                            <span>{post.comments ? post.comments.length : 0}</span>
                        </span>
                        <span className="flex items-center space-x-1">
                            <svg className="w-4 h-4" fill={post.likes > 0 ? "currentColor" : "none"} stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/></svg>
                            <span>{post.likes || 0}</span>
                        </span>
                    </div>
                    <span className="text-blue-500 font-medium opacity-0 group-hover:opacity-100 transition-opacity">{translations.readMore} &rarr;</span>
                </div>
                </div>
            ))}
            </div>
        )}
        </div>
    );
  };

  return (
    <div className="w-full">
      {view === 'list' && renderListView()}
      {view === 'create' && renderCreateView()}
      {view === 'detail' && renderDetailView()}
    </div>
  );
};

export default Board;